namespace: ifrs9

kube-prometheus-stack:
  fullnameOverride: ifrs9-monitoring
  grafana:
    defaultDashboardsEnabled: true
    service:
      type: ClusterIP
    adminPassword: admin
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      retention: 15d
  alertmanager:
    enabled: true

jaeger-operator:
  rbac:
    clusterRole: true

elasticsearch:
  replicas: 1
  minimumMasterNodes: 1
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 4Gi
  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 20Gi

kibana:
  service:
    type: ClusterIP

fluent-bit:
  serviceMonitor:
    enabled: true
  config:
    outputs: |
      [OUTPUT]
          Name  es
          Match *
          Host  elasticsearch-master.ifrs9.svc.cluster.local
          Port  9200
          Index ifrs9-logs
          Logstash_Format On

