apiVersion: v1
kind: ConfigMap
metadata:
  name: ifrs9-config
  namespace: {{ .Values.namespace }}
data:
  RULES_CONFIG: |-
    # placeholder for rules and orchestration configs
    default_timeout: 60
    retry_backoff_sec: 2

