apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: ifrs9
    {{- if .Values.global.serviceMesh.enabled }}
    {{- $kv := split "=" .Values.global.serviceMesh.injectLabel }}
    {{ index $kv 0 }}: {{ index $kv 1 | quote }}
    {{- end }}

