{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ifrs9-agents
  namespace: {{ .Values.namespace }}
spec:
  namespaceSelector:
    matchNames: [{{ .Values.namespace | quote }}]
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          {{- range .Values.agents }}
          - ifrs9-{{ .name }}
          {{- end }}
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
{{- end }}

