version: '3.8'

services:
  locust:
    image: locustio/locust:2.29.1
    container_name: ifrs9-locust
    environment:
      - LOCUST_HEADLESS=${LOCUST_HEADLESS:-false}
      - LOCUST_USERS=${LOCUST_USERS:-100}
      - LOCUST_SPAWN_RATE=${LOCUST_SPAWN_RATE:-10}
      - LOCUST_RUN_TIME=${LOCUST_RUN_TIME:-15m}
      - LOCUST_HOST=${LOCUST_HOST:-http://ifrs9-api:8080}
    ports:
      - "8089:8089"
    volumes:
      - ../../testing/locustfile.py:/mnt/locust/locustfile.py:ro
    command: -f /mnt/locust/locustfile.py --host=${LOCUST_HOST}
    restart: unless-stopped

