# IFRS9 Rules Engine Configuration
# This file contains all configurable parameters for IFRS9 compliance calculations

# Staging Rules Configuration
staging_rules:
  # Days Past Due Thresholds
  stage_1_dpd_threshold: 30
  stage_2_dpd_threshold: 90
  stage_3_dpd_threshold: 90  # Same as stage 2, but with additional criteria
  
  # Significant Increase in Credit Risk (SICR) Detection
  sicr_detection:
    enabled: true
    pd_multiplier_threshold: 2.0  # PD must increase by this factor
    credit_score_decline_threshold: 100  # Points decline in credit score
    ltv_ratio_threshold: 0.95  # High LTV ratio indicator
    dti_ratio_threshold: 0.45   # High DTI ratio indicator
    
  # ML Integration Settings
  ml_integration:
    enabled: true
    weight_ml_predictions: 0.7  # Weight given to ML predictions (0-1)
    weight_rule_based: 0.3      # Weight given to rule-based decisions
    confidence_threshold: 0.8   # Minimum confidence for ML predictions
    fallback_to_rules: true     # Use rules if ML fails
    
# Risk Parameter Calculations
risk_parameters:
  # Probability of Default (PD) Configuration
  pd_calculation:
    use_ml_predictions: true
    minimum_pd_stage1: 0.0005  # 5 basis points minimum for Stage 1
    maximum_pd_stage1: 0.04    # 4% maximum for Stage 1
    minimum_pd_stage2: 0.05    # 5% minimum for Stage 2
    maximum_pd_stage2: 0.99    # 99% maximum for Stage 2
    stage3_pd: 1.0             # 100% PD for Stage 3 (default)
    
  # Loss Given Default (LGD) Configuration  
  lgd_calculation:
    secured_loans:
      mortgage:
        minimum_lgd: 0.20
        recovery_rate_factor: 1.0
      auto:
        minimum_lgd: 0.25
        recovery_rate_factor: 0.9
      other_secured:
        minimum_lgd: 0.30
        recovery_rate_factor: 0.8
    unsecured_loans:
      personal:
        minimum_lgd: 0.45
        recovery_rate_factor: 0.5
      credit_card:
        minimum_lgd: 0.70
        recovery_rate_factor: 0.3
      other_unsecured:
        minimum_lgd: 0.60
        recovery_rate_factor: 0.4
        
  # Exposure at Default (EAD) Configuration
  ead_calculation:
    credit_card_ccf: 1.1      # Credit Conversion Factor for credit cards
    line_of_credit_ccf: 0.75  # CCF for lines of credit
    term_loan_ccf: 1.0        # CCF for term loans

# Expected Credit Loss (ECL) Configuration
ecl_calculation:
  # Discounting Parameters
  discounting:
    enabled: true
    risk_free_rate: 0.025      # 2.5% risk-free rate
    economic_cycle_adjustment: 0.005  # Additional adjustment for economic cycle
    
  # Time Horizon Configuration
  time_horizons:
    stage1_months: 12          # 12-month ECL for Stage 1
    stage2_lifetime_cap_years: 30  # Maximum lifetime for Stage 2 ECL
    stage3_lifetime_cap_years: 30  # Maximum lifetime for Stage 3 ECL
    
  # Forward-Looking Adjustments
  forward_looking:
    enabled: true
    economic_scenarios:
      base_weight: 0.5
      adverse_weight: 0.3
      severe_adverse_weight: 0.2
    macroeconomic_factors:
      gdp_growth_impact: 0.1
      unemployment_impact: 0.15
      interest_rate_impact: 0.05

# Validation and Audit Configuration
validation:
  # Business Rule Validation
  enable_validation: true
  max_pd_increase_factor: 10.0    # Maximum allowed PD increase
  max_ecl_portfolio_percentage: 0.25  # ECL cannot exceed 25% of portfolio
  
  # Audit Trail Configuration
  audit_trail:
    enabled: true
    log_all_calculations: true
    include_intermediate_steps: true
    retention_days: 2555  # 7 years retention
    
# Economic Scenarios Configuration
economic_scenarios:
  base_scenario:
    name: "Base Case"
    gdp_growth: 0.025
    unemployment_rate: 0.05
    interest_rate_environment: "stable"
    
  adverse_scenario:
    name: "Adverse Case" 
    gdp_growth: -0.01
    unemployment_rate: 0.08
    interest_rate_environment: "rising"
    
  severe_adverse_scenario:
    name: "Severe Adverse Case"
    gdp_growth: -0.05
    unemployment_rate: 0.12
    interest_rate_environment: "volatile"

# Model Configuration
model_settings:
  model_path: "/opt/airflow/models/"
  fallback_to_simple: true
  health_check_frequency_hours: 24
  model_refresh_threshold_days: 90
  
# Output Configuration  
output_settings:
  # File Output Paths
  results_path: "/opt/airflow/data/processed/ifrs9_results/"
  audit_path: "/opt/airflow/data/audit/ifrs9_audit/"
  
  # File Formats
  output_formats: ["parquet", "json"]
  compression: "snappy"
  
  # Reporting
  generate_summary_report: true
  include_model_explanations: true
  export_stage_distributions: true
